CREATE DATABASE LIVRARIA;

CREATE TABLE LIVROS(
	LIVRO VARCHAR (100),
	AUTOR VARCHAR (100),
	SEXO CHAR (1),
	PAGINAS INT (5), 
	EDITORA VARCHAR (30), 
	VALOR FLOAT(10,2), 
	UF CHAR (2), 
	ANO INT (4)
);
 /* VERIFICANDO OS BANCOS */
SHOW DATABASES;

/* CONECTANDO A UM BANCO */
USE LIVRARIA; 

INSERT INTO LIVROS VALUES ('Cavaleiro Real', 'Ana Claudia',	'F', 465, 'Atlas', 49.9, 'RJ', 2009);
INSERT INTO LIVROS VALUES ('SQL para leigos', 'João Nunes', 'M', 450, 'Addison', 98, 'SP', 2018);
INSERT INTO LIVROS VALUES ('Receitas Caseiras', 'Celia Tavares', 'F', 210, 'Atlas', 45, 'RJ', 2008);
INSERT INTO LIVROS VALUES ('Pessoas Efetivas', 'Eduardo Santos', 'M', 390, 'Beta', 78.99, 'RJ', 2018);
INSERT INTO LIVROS VALUES ('Habitos Saudáveis', 'Eduardo Santos', 'M', 630, 'Beta', 150.98, 'RJ', 2019);
INSERT INTO LIVROS VALUES ('A Casa Marrom', 'Hermes Macedo', 'M', 250, 'Budda', 60, 'MG', 2016);
INSERT INTO LIVROS VALUES ('Estacio Querido', 'Geraldo Francisco', 'M', 310, 'Insignia', 100, 'ES', 2015);
INSERT INTO LIVROS VALUES ('Pra sempre amigas', 'Leda Silva', 'F', 510, 'Insignia', 78.98, 'ES', 2011);
INSERT INTO LIVROS VALUES ('Copas Inesqueciveis', 'Marco Alcantara', 'M', 200, 'Larson', 130.98, 'RS', 2018);
INSERT INTO LIVROS VALUES ('O poder da mente', 'Clara Mafra', 'F', 120, 'Continental', 56.58, 'SP', 2017);

/* TODOS OS DADOS */

SELECT * FROM LIVROS;

/* NOME DO LIVRO E DA EDITORA */

SELECT LIVRO, EDITORA FROM LIVROS;

/* NOME DO LIVRO E A UF DOS LIVROS PUBLICADOS */

SELECT LIVRO, UF FROM LIVROS
WHERE SEXO = 'M';

/* NOME DO LIVRO E NÚMERO DE PÁGINAS PUBLICADOS POR AUTORES DO SEXO FEMININO */

SELECT LIVRO, PAGINAS FROM LIVROS
WHERE SEXO = 'F';

/* VALORES DOS LIVROS DAS EDITORAS DE SÃO PAULO */

SELECT VALOR FROM LIVROS
WHERE UF = 'SP';

/* DADOS DOS AUTORES DO SEXO MASCULINO QUE TIVERAM LIVROS PUBLICADOS POR SP E RJ */

SELECT AUTOR, SEXO FROM LIVROS
WHERE SEXO = 'M' 
AND UF = 'SP' OR UF = 'RJ';

/* OPERADORES LÓGICOS */
/* OR - PARA QUE A SAÍDA DA QUERY SEJA VERDADEIRA, BASTA QUE APENAS UMA CONDIÇÃO SEJA VERDADEIRA*/
/* AND - PARA QUE A SAÍDA SEJA VERDADEIRA TODAS AS CONDIÇÕES PRECISAM SER VERDADEIRAS*/

/* OR - OU */

SELECT AUTOR, SEXO, UF FROM LIVROS
WHERE SEXO = 'M' OR UF LIKE '&RJ';

SELECT AUTOR, SEXO UF FROM LIVROS
WHERE SEXO = 'F' OR UF LIKE '%ESTACIO';

/* AND - E */

SELECT AUTOR, SEXO, UF FROM LIVROS 
WHERE SEXO = 'M' AND UF LIKE '%RJ';

SELECT AUTOR, SEXO UF FROM LIVROS
WHERE SEXO = 'F' AND UF LIKE '%ESTACIO';